puppetlabs/beaker-puppet

lib/beaker-puppet.rb
porting this commit:
https://github.com/puppetlabs/beaker-template/pull/8/commits/c19ca0b343a8723db73f1a6b956c86723ad2ee3c
into this repo. It was easier to pull in
the changes themselves rather than use
other methods.
=> (MAINT) fix DSL inclusion

README.md
=> (MAINT) improve README description

lib/beaker-puppet/install_utils/foss_utils.rb, spec/beaker-puppet/install_utils/foss_utils_spec.rb
This commit modifies the `install_puppet_agent_dev_repo_on` method
to install the puppet-agent package if the host is on ec2 and el.
This is done because the ec2 instance does not have access to the
default dev repo.
=> (BKR-1147) Fail to pkg install on ec2 for dev-repo

lib/beaker-puppet/install_utils/foss_utils.rb
This commit moves the setting of the values for `opts` into the block
for the hosts submitted to the `install_puppet_agent_dev_repo_on`
method. Prior to this commit, the `opts[:download_url] would become
corrupted by inheriting the value from the previous host run and
appending to it.
=> (BKR-1159) Reset opts in install_puppet_agent_dev_repo_on

lib/beaker-puppet/install_utils/foss_utils.rb, spec/beaker-puppet/install_utils/foss_utils_spec.rb
This is needed to be able to run the hardware testing automation for
ubuntu 16.04 Power8 hosts.
=> (BKR-1164) Add ubuntu to the platform list in remove_puppet_on

spec/beaker-puppet/install_utils/foss_utils_spec.rb
Changes in beaker core resulted in failures here; these changes update
the spec tests to use an actual Beaker::Platform object instead of a
String object.
=> (MAINT) fix windows spec failures

lib/beaker-puppet/install_utils/foss_utils.rb
@melissa noticed while updating downstream
projects that `dev_builds_repos` was an option
beaker declared as necessary, but wasn't in use.
it looks like it was removed in BKR-648
(github.com/puppetlabs/beaker/pull/1044), but
these mentions lingered. This PR removes them,
so hopefully we won't get as confused next time.
=> (MAINT) remove `dev_builds_repos` mentions

beaker-puppet.gemspec, lib/beaker-puppet/install_utils/foss_utils.rb, spec/beaker-puppet/install_utils/foss_utils_spec.rb
1. beaker-puppet did not have an explicit nokogiri dependency declaration as it
was using the one provided with beaker-core. Beaker-core is will not have
nokogiri as a dependency soon. Therefore adding oga as a dependency for
beaker-puppet.
2. The old get_latest_puppet_agent_build_from_url method did not return the
right version number even on the url provided in the documentation of the
method. The only url it returned a correct verion was:
"https://downloads.puppetlabs.com/mac/10.9/PC1/x86_64"
With the new code some of the URLs that it parses correctly include:
"https://downloads.puppetlabs.com/mac/10.9/PC1/x86_64"
"https://downloads.puppetlabs.com/mac/10.10/PC1/x86_64"
"https://downloads.puppetlabs.com/mac/10.11/PC1/x86_64"
"https://downloads.puppetlabs.com/mac/10.12/PC1/x86_64" …
=> (BKR-1185) Use Oga instead of Nokogiri

lib/beaker-puppet.rb, lib/beaker-puppet/helpers/puppet_helpers.rb, lib/beaker-puppet/install_utils/foss_utils.rb, lib/beaker-puppet/install_utils/puppet5.rb, spec/beaker-puppet/install_utils/puppet5_spec.rb
**Note** that this does not plug into `install_puppet` or `install_puppet_agent_on` methods at this point, it only provides basic puppet5 install functionality using the new `puppet5_install` method.
**Note** that that doesn't need to block merging this work, as those values need outside information that we don't have right now & can get in in a subsequent PR.
=> (BKR-1118) add puppet5 install method

Gemfile
This is needed for acceptance testing in production. It should not have an effect on local testing.
=> (maint) Add beaker-abs to Gemfile

lib/beaker-puppet/install_utils/puppet5.rb
This commit removes some unnecessary debugging information. It was good
to have, but it was spitting out a huge amount of unnecessary
information. It was bogging down beaker runs that use this method.
=> (maint) Remove unnecessary logger information

lib/beaker-puppet/install_utils/puppet5.rb, spec/beaker-puppet/install_utils/puppet5_spec.rb
On Windows, the "install_from_build_data_url" method was trying to
install the artifact as a cygwin package which won't work for MSIs.
Instead use the beaker method for installing as an MSI. Note the
"install_msi_on" method is specific to the puppet-agent package, because
it will ensure the puppet service is stopped before installing and will
install it as a Manual service. In the future we may want to
differentiate between the puppet-agent project and others, and use
"generic_install_msi_on" for the latter.
=> (BKR-1343) Install as an MSI on Windows

lib/beaker-puppet/install_utils/puppet5.rb, spec/beaker-puppet/install_utils/puppet5_spec.rb
This is blocked on https://github.com/puppetlabs/beaker-puppet/pull/23
Previously the if/elsif block set onhost_package_file for some, but not
all hosts. Then a second if/elsif block called different install methods
based on the platform variant and the above variable.
This commit uses a single case/when statement to branch. It makes it
clearer that EOS calls install_from_file, OSX uses the single argument
version of install_local_package, while Solaris uses the two argument
version. Also Windows uses a different installation method entirely.
=> (maint) Refactor puppet5 install logic

tasks/ci.rake
We decided to isolate this test to the puppet project. The tests that it
pulls are very specific to puppet itself, so we'd rather implement this
on a per project basis. I forgot to pull out the references to the quick
=> (maint) Remove references to 'ci:test:quick'

tasks/ci.rake
When run with the absolute path, tests on Japanese windows end up with
an unescaped `%` in the path. This results in an error `#<ArgumentError:
malformed format string - %D>`. If we ensure these paths are relative,
we should be able to avoid this failure.
=> (maint) Pre suite paths must be relative

tasks/ci.rake
Prior to this commit, when running acceptance tests from the rakefile,
we were always destroying the host if the tests passed. However, this
didn't take into account when users passed in `--preserve-hosts=always`.
This commit ensures we skip the `beaker destroy` step whenever the user
sets `--preserve-hosts=always` in the OPTIONS setting.
=> (BKR-1443) Ensure we do not destroy hosts if specified

tasks/ci.rake
This commit adds information for additional environment variables
available for use when running acceptance tests.
=> (maint) Add information about additional ENV vars

lib/beaker-puppet/helpers/puppet_helpers.rb
This PR adds in the agent lock check to after the puppet service
is stopped. There is a window from when we do the initial check on
the agent lock, to where we stop the service.
During that window if a Puppet run goes off the method will end with
the puppet service stopped, but a run in progress. This change will
hopefully cause this to no longer occur.
=> (BKR-1453) Ensure no agent lock after stopping puppet service

lib/beaker-puppet/helpers/puppet_helpers.rb, lib/beaker-puppet/install_utils/module_utils.rb, spec/beaker-puppet/install_utils/module_utils_spec.rb
The current beaker workflow with a custom forge host means stubbing it
in /etc/hosts. This doesn't work because it uses SSL and then the
certificate validation fails. By using the --module-repository option it
just works and even allows you to use plain http and a different port.
Tested with https://github.com/unibet/puppet-forge-server to use caching
to avoid the slow puppet forge.
=> Use --module-repository for a custom forge

lib/beaker-puppet/install_utils/puppet5.rb, setup/common/040_ValidateSignCert.rb, spec/beaker-puppet/install_utils/puppet5_spec.rb
This is a partial revert of commit 5a9c90f. When installing
puppet-agent packages we need to use the install_msi_on helper, because
it sets the service startup type to manual, which prevents the service
from starting and sending a CSR before we've configured the agent. It
also verifies that the service startup is correct after installation,
otherwise you can get transient failures if the background agent service
is running while performing puppet agent -t runs in the foreground.
When installing MSI packages for other projects, use the
generic_install_msi_on method.
=> Use puppet-agent specific helper when installing the MSI

lib/beaker-puppet/install_utils/foss_utils.rb
Please see https://tickets.puppetlabs.com/browse/CPR-570 for additional
details.
Sles 11 has some old and wonky behavior. We can't automatically import
our gpg keys provided with the release package like we do for every
other rpm-based platform. Once we install the release packages, we need
to manually import the keys. This will allow us to install signed
packages from our public repos.
=> (CPR-570) Import the gpg signing key on sles 11

lib/beaker-puppet/install_utils/foss_utils.rb
apt is more strict by default in Ubuntu 18.04, so this config option is
needed to allow apt to update repository data from our unsigned repos on
builds.
=> (BKR-1462) Allow unsigned apt repositories for Ubuntu 18.04 hosts

lib/beaker-puppet/install_utils/foss_utils.rb
Parameter "opts" on Method "install_puppet_on" now defaults to "options", which contains the information gained from the CONFIG section in the nodeset definition.
This has been copied from "install_puppetlabs_release_repo_on"
=> BKR-1465 - install_puppet_on -"opts" defaults "options"

lib/beaker-puppet/install_utils/puppet5.rb, spec/beaker-puppet/install_utils/puppet5_spec.rb
Allows the environment variable BEAKER_PACKAGING_PLATFORMS to override
the default packaging platforms specified for hosts by
beaker-hostgenerator in `host_urls`. BEAKER_PACKAGING_PLATFORMS should
be a comma-separated list with entries of the format
`<platform-name>=<packaging-platform-name>`.
[Here's an example run of puppet-agent and puppet acceptance](https://jenkins-master-prod-1.delivery.puppetlabs.net/view/puppet-agent/view/ad-hoc/job/platform_puppet-agent-extra_puppet-agent-integration-suite_adhoc-ad_hoc/204/), with `
BEAKER_PACKAGING_PLATFORMS="aix-7.1-power=aix-6.1-power,aix-7.2-power=aix-6.1-power"` set on puppet-agent only; The puppet-agent tests install the 6.1 package on 7.1 and 7.2, and the puppet tests (which don't use the environment variable) fail, because they still look …
=> (BKR-1484) Packaging platform overrides for puppet5 install utils

acceptance/tests/create_tmpdir_on_test.rb, lib/beaker-puppet/helpers/puppet_helpers.rb, spec/beaker-puppet/helpers/puppet_helpers_spec.rb
Also moves spec and acceptance tests. Corresponds to puppetlabs/beaker#1531 Note that this moves the fixed and improved version; wrote it, might as well keep it.
Moved to beaker-puppet because the only invocation was already here: https://github.com/puppetlabs/beaker-puppet/blob/53927095e45ac792a42079ad4bce1fa4d059b005/lib/beaker-puppet/helpers/puppet_helpers.rb#L883
=> (BKR-496) Move create_tmpdir_on from beaker

acceptance/tests/create_tmpdir_on_test.rb, lib/beaker-puppet/helpers/puppet_helpers.rb, spec/beaker-puppet/helpers/puppet_helpers_spec.rb
Reverts puppetlabs/beaker-puppet#57
This needs to wait to merge just before Beaker 4.0 release.
=> Revert "Revert "(BKR-496) Move create_tmpdir_on from beaker""

lib/beaker-puppet.rb, setup/aio/010_Install_Puppet_Agent.rb, setup/aio/011_Install_Puppet_Server.rb, setup/aio/012_Finalize_Installs.rb, setup/gem/010_GemInstall.rb, setup/git/000_EnvSetup.rb, setup/git/010_TestSetup.rb, spec/beaker-puppet/install_utils/puppet_utils_spec.rb
Assorted fixes for running puppet/acceptance that weren't caught during acceptance testing due to CI configuration conflicts.
=> (BKR-1509) Beaker 4.0 Compatibility

lib/beaker-puppet/install_utils/foss_utils.rb, lib/beaker-puppet/install_utils/puppet_utils.rb, spec/beaker-puppet/install_utils/foss_utils_spec.rb, spec/beaker-puppet/install_utils/puppet_utils_spec.rb
Legacy agent installation job testing older agents with new PE versions
in Integration CI does not use frictionless installation method. Instead
it downloads the agent package from pm.puppetlabs.com. Agent
installation in that case fails since the puppet_collection value is set
to default 'PC1' instead of 'puppet5' causing the construction of wrong
'onhost_copied_file' path. Added a method to return the correct
puppet_collection depending on the agent version and use that value
instead of the default
=> PE-24898 Set puppet collection value associated with agent version

lib/beaker-puppet.rb, lib/beaker-puppet/helpers/host_helpers.rb
PE-16486 required checking of file permissions of certain files and as part of
that work some generic utility type methods were identified. And reviewers suggested
they be made part of beaker-puppet (and not beaker as its maintainers indicated)
for more broader use.
=> (MAINT) Adding some generic host helper utility methods

lib/beaker-puppet/helpers/facter_helpers.rb, spec/beaker-puppet/helpers/facter_helpers_spec.rb
This code adds json to the options of fact_on() and parses the result. This means that fact() and fact_on() preserve the structure and data types of facts.
=> (BKR-1510) make fact helpers support structured facts

lib/beaker-puppet/install_utils/aio_defaults.rb
In PA-1923, we're updating install paths in Windows agents so that they more closely match the paths used in \*nix agents -- this PR adds the new location of the vendored ruby executable to the default PATHs set up by beaker while installing puppet-agent. We could make this distinction based on the collection name, but it seemed less disruptive to just include all the possible paths at once.
The pathing work hasn't been merged in puppet-agent yet (the PR is [here](https://github.com/puppetlabs/puppet-agent/pull/1517)), so I'm putting the blocked label on this PR for the moment while I finish testing everything there.
=> (BKR-1445) Update Windows agent paths for puppet6

lib/beaker-puppet/helpers/puppet_helpers.rb, setup/common/040_ValidateSignCert.rb, spec/beaker-puppet/helpers/puppet_helpers_spec.rb
Previously one of the `puppet --version` checks was missing a call to
`stdout` on the result of the command, causing the version checking
message to crash when it received a Beaker::Result instead of a string.
This commit adds the missing stdout calls.
=> (maint) Get stdout of calls to `puppet --version`

lib/beaker-puppet/helpers/puppet_helpers.rb
We were seeing race conditions in ci for frictionless installs on
solaris and ubuntu (slower platforms?) where the frictionless install
script starts the puppet service, which runs the agent, which begins the
csr submission.
The 'puppetserver ca list --all' output now returns 'Requested' certs in one
section and 'Signed' certs in another. The test for a lack of
'Requested' section works so long as we haven't gotten here before the
agent service has completed submitting the CSR.
To work around this, verify that hostnames are all signed by checking
that we have no Requested, and that therefore we're finding hostnames in
the Signed section.
=> (PE-25146) Check for hostnames when puppetserver signing

lib/beaker-puppet/helpers/puppet_helpers.rb, setup/common/040_ValidateSignCert.rb, spec/beaker-puppet/helpers/puppet_helpers_spec.rb
This cherry-picks a couple of follow-up commit to the `puppetserver ca` switchover, that are needed for using beaker-puppet in PE with Puppet 6.
=> Backport additional `puppetserver ca` fixes

lib/beaker-puppet/helpers/facter_helpers.rb, spec/beaker-puppet/helpers/facter_helpers_spec.rb
Since https://github.com/puppetlabs/beaker-puppet/pull/59 `fact_on`
stopped working with symbols for fact names. (The documentation says it takes a String for `name` so only worked by chance previously).
In `puppet/collectd` we had a test that had started failing (easy enough to fix), and some that were being silently skipped. https://github.com/voxpupuli/puppet-collectd/pull/858
=> (maint) Validate `fact_on` `name` parameter

lib/beaker-puppet/helpers/facter_helpers.rb, spec/beaker-puppet/helpers/facter_helpers_spec.rb
The fact name can have spaces. Thus, it should be quoted before it is passed
into the shell.
=> (PA-2183) Quote fact name in fact_on helper

beaker-puppet.gemspec, tasks/ci.rake
We need to be able to preserve the state of the hosts that is set up
during the pre-suite runs. We previously were relying on beaker to
initiate this on every invocation, but that behavior was removed in
beaker 4. This commit takes advantage of a new flag that will cause
invocations of `beaker exec` to save the host state. We really only want
to do this when we're running pre-suites.
=> (PUP-9136) Ensure state is preserved between runs

setup/git/000_EnvSetup.rb, setup/git/010_TestSetup.rb
Unfortunately there isn't a ticket for this work.
However, there are two things that are happening as a part of this
commit.
First, we don't want to try to download or unpack the runtime tarball.
If we're using docker to run the tests, the user should be pulling an
image that already has all the stuff that runtime provides. Hopefully
they're using a relatively new image that corresponds to whatever branch
they're working on. This is a big assumption, but it allows us to remove
the requirement that this be run on infrastructure that is only internal
to puppet.
Next, we allow dependencies to be installed from a directory that has
been bind mounted into the docker container. This will let us run tests
against a code base that we can be modifying as we go. We don't have to
figure out how to …
=> (maint) Add docker specifics to git testing

setup/common/025_StopFirewall.rb
If we're on a system that should have iptables but doesn't for some
reason, then we don't need to purge iptables.
This happens on systems like docker, where some images just don't have
that. We don't need to manage it.
=> (maint) If iptables doesn't exist, don't fail

lib/beaker-puppet/install_utils/foss_defaults.rb, spec/beaker-puppet/install_utils/foss_utils_spec.rb
This is particularly important because apt.puppetlabs.com and
yum.puppetlabs.com don't support IPv6 resolution.
=> (MAINT) update spec tests to use puppet.com

tasks/ci.rake
This wraps the destroy subcommand in an ensure block to make sure
that we always get rid of hosts even if other subcommands cause a
rake failure after provisioning.
=> (BKR-1558) make sure we destroy hosts for ci:test:* task execution

lib/beaker-puppet/install_utils/module_utils.rb, spec/beaker-puppet/install_utils/module_utils_spec.rb
When using `BEAKER_provision=no` the `host['distmoduledir']` is undefined. This means we need to autodetect it. For this we can let puppet print its config for us. This is in fact a much more fool proof method than relying on some variable so we prefer this now.
Also removes an unused variable.
=> Autodetect the target module dir in copy_module_to

lib/beaker-puppet/install_utils/foss_utils.rb, lib/beaker-puppet/install_utils/puppet_utils.rb, setup/common/025_StopFirewall.rb, spec/beaker-puppet/install_utils/puppet_utils_spec.rb
Adds several new helpers to accommodate the use of beaker-puppet in acceptance testing for the puppetlabs-puppet_agent module. See the commit messages for more detail, but in short:
1. Extracts a `stop_firewall_with_puppet_on` helper method from the corresponding rake setup task
2. Adds two new methods for looking up the names of puppet collections, and deprecates the existing one
3. Adds a helper to determine whether the controlling host has access to Puppet's internal dev builds
4. Adds helpers to report the installed versions of puppet-agent or puppetserver
Although this shouldn't change the behavior of the "stop firewall" setup task, that task is used in puppet-agent's CI -- I will do an ad-hoc run of those tests using these changes before unblocking this.
=> (BKR-1560) Updates to support puppet_agent module testing

lib/beaker-puppet/install_utils/puppet5.rb, spec/beaker-puppet/install_utils/puppet5_spec.rb
Makes error messages about missing build metadata from SHA.yaml files in
`install_from_build_data_url` a little more straightforward
=> (maint) Simplify missing SHA.yaml error message

lib/beaker-puppet/install_utils/foss_utils.rb, spec/beaker-puppet/install_utils/foss_utils_spec.rb
puppet-agent's test suite relies on a reusable test file,
setup/common/011_Install_Puppet_Server.rb, to install puppetserver on
puppet masters before the tests run. This extracts the logic from that
test file into a helper method, `install_puppetserver_on`, which does
the same thing.
=> (BKR-1560) Add install_puppetserver_on helper

lib/beaker-puppet/install_utils/foss_utils.rb, lib/beaker-puppet/install_utils/puppet_utils.rb, spec/beaker-puppet/install_utils/foss_utils_spec.rb
Three small commits here:
- Use the `facter` helper in `puppet_agent_version_on` - This seems to be more reliably correct when executing facter on windows where the PATH may not be updated correctly on the SUT.
- Consistently downcase collection names - There are no puppet collections that use capital letters, so always convert any collection parameters to `install_puppet_agent_on` to lowercase (instead of expecting the caller to get it right -- this is often confusing for PC1/pc1)
- Pass host targets along to the install method during puppetserver install (my mistake)
=> A few small puppet helper fixes

lib/beaker-puppet/install_utils/puppet_utils.rb
These would return the execution result when the exit code wasn't zero.
=> (maint) return nil explicitly for agent/server version helpers

lib/beaker-puppet/install_utils/foss_utils.rb
Avoid risk of RunTime errors related to mutating frozen strings by not modifying puppet_collection in place.
=> (maint) Avoid mutating frozen string

setup/git/010_TestSetup.rb
It turns out `agent` and `agents` are equivalent if you don't explicitly set
`agent` to something. Who knew! The loop that this exists in we refer to
the individual servers as `host`, not `agent` as I had previously, and
incorrectly, assumed.
This resulted in some strange errors depending on how many agents we had
defined for a given run. `agent`, and I assume `agents` as well, returns
a host object if there is only one host with the agent role and it will
return an array of hosts if there are multiple hosts with the agent
role.
=> (maint) `agent` should be `host`

lib/beaker-puppet/install_utils/module_utils.rb
The PE utilities use ./tmp to store the puppet agent installation files
however during a module install these files are also copied.  This causes,
in my case, beaker acceptance runs to take 10+ minutes longer than they
should for no reason.  (Australia -> US, lots of MSI installers).
This commit adds ./tmp as a directory to ignore.
=> (maint) Exclude tmp directory on module installation

acceptance/pre_suite/pkg/install.rb
Previously, it was not installing anything on the agent, resulting
in failures in the later tests. Additionally, moving the puppet/agent
version to 5 as 4 is in "deep maint" mode.
=> (MAINT) Fix test:acceptance:pkg

setup/git/000_EnvSetup.rb
We don't have a pipeline that regularly updates or publishes the docker
rumtime image. If we remove this assumption, we can use generic docker
images for acceptance
=> (maint) Remove assumption that we have runtime on docker

lib/beaker-puppet/install_utils/foss_utils.rb
(maint) Added debian 10 or higher to allow insecure repo like for ubuntu
This commit fixes the following:
When apt-get update is run against our builds our artifact repo it will throw an error saying that The repository is not signed.
By adding  the flag --allow-insecure-repository it will thrown a warning instead of an error.
More details in: https://tickets.puppetlabs.com/browse/BKR-1462
=> (maint) Added debian 10 or higher to allow insecure repo

lib/beaker-puppet/install_utils/foss_utils.rb
The non-local return caused beaker-puppet to install puppet-agent on the
first host in the `hosts` array. Use if/else to avoid the non-local
return.
=> (BKR-1587) Install non-latest builds on all hosts

lib/beaker-puppet/install_utils/foss_utils.rb, spec/beaker-puppet/install_utils/foss_utils_spec.rb
Instead of globally disabling package signing checks we can mark our development
repos as trusted. This allows both the repository and its packages to be
unsigned.
The previous implementation is more broad and more specific than needed, in
that it applied to all repositories and required separate settings for unsigned
repositories and unsigned packages. The setting for unsigned packages was
missing, which caused failures on the platforms that required it.
I've tested this on the oldest version of debian available in vmpooler, which
does not support this flag, and it seems to ignore the flag and still work.
=> (maint) Mark dev repos as trusted

setup/common/040_ValidateSignCert.rb
To ensure individual tests don't need to set `--server <hostname>` set
it in the presuite for all types (git, aio, etc). Note Host#hostname is
the same as Host#to_s, but I chose the former for its explicitness.
=> (BKR-1598) Set server hostname

lib/beaker-puppet/helpers/puppet_helpers.rb
If puppet.conf contained a setting without a preceding section, as can happen
due to PUP-4755, then the 'lay_down_new_puppet_conf' method created a 'global'
section for that setting, however, that is not a valid puppet section name.
Specify the default section name as 'main' so it matches puppet's behavior.
=> (BKR-1600) Default puppet settings to `main` section

lib/beaker-puppet/install_utils/foss_utils.rb
This commit adds debug output for the repo config contents before and after
gsubbing. Filesync tests have been experiencing a transient failure where
debian repo contents are malformed. We've narrowed down the failure to this
method, somewhere between pulling down the file and scp'ing it to the host.
This debug output is intended to give us more insight into what is causing this
issue, but I haven't actually been able to reproduce the issue since making
this change. Perhaps this is enough to eliminate the transient altogether.
¯\_(ツ)_/¯
=> (RE-12690) Add debug output to `install_repo_configs_from_url`

lib/beaker-puppet/install_utils/foss_utils.rb
This commit updates the regex we match against when adding `[trusted=yes]` to
debian repo files. Previously, we sometimes ended up with `[trusted=yes]`
getting added twice if the `gsub` was re-run, since we were only matching
against 'deb '. This change should ensure that this only ever gets added once.
=> (RE-12690) Be more explicit about when to gsub

tasks/ci.rake
When generating a hosts file, we should be able to pass in different
hypervisor options.
=> (maint) Allow custom hypervisor settings

lib/beaker-puppet/install_utils/puppet5.rb, lib/beaker-puppet/install_utils/puppet_utils.rb, lib/beaker-puppet/install_utils/windows_utils.rb, spec/beaker-puppet/install_utils/puppet5_spec.rb, spec/beaker-puppet/install_utils/windows_utils_spec.rb
* Change calls of 'type' to 'more' to handle paths with spaces
* Check to make sure that puppet is in the connection path and reboot
otherwise. This fixes issues with Windows SSH servers.
* Fix the path calls to the versions.txt file
=> Fix Windows Support

lib/beaker-puppet/install_utils/puppet5.rb, lib/beaker-puppet/install_utils/puppet_utils.rb, lib/beaker-puppet/install_utils/windows_utils.rb, spec/beaker-puppet/install_utils/puppet5_spec.rb, spec/beaker-puppet/install_utils/windows_utils_spec.rb
This reverts commit 99eb9dca358d0a6122b56dc14521b470d049f7b8, reversing
changes made to acda051301824c84b5e01f777211e9a37513ac1e.
Adding `more` does note resolves the spaces in path and it
causes all agent pipelines to fail on widnows.
=> Revert "Merge pull request #129 from trevor-vaughan/windows_paths"

Gemfile, lib/beaker-puppet/install_utils/foss_utils.rb, lib/beaker-puppet/install_utils/windows_utils.rb, spec/beaker-puppet/install_utils/windows_utils_spec.rb
* Second cut at fixing support for newer versions of Windows
* Windows updates
* Update to use file_contents_on instead of calling out to either 'type'
or 'more'
* Reboot if puppet is not in the system PATH
=> Update to remove issues with type/more commands

lib/beaker-puppet/install_utils/foss_utils.rb, spec/beaker-puppet/install_utils/foss_utils_spec.rb
There does not appear to be any support to enable the installation of a Windows package via the `:package_proxy` setting. This contribution would add that support.
=> (maint) Enable Windows hosts to use the package_proxy

lib/beaker-puppet/install_utils/windows_utils.rb
The powershell invocation in log_file_on uses a powershell helper that needs additional escaping for log file.
=> (maint) Add extra escape chars in msi-log

lib/beaker-puppet/helpers/host_helpers.rb, spec/beaker-puppet/helpers/host_helpers_spec.rb
When the tests are run locally without cygwin on a windows machine, the ruby_command method causes an error. 
With this fix a valid cmd command is returned for this scenario.
=> (BKR-1654) ruby_command should work on windows localhost

CODEOWNERS
We are planning to transfer this repo to the voxpupuli organization, and
once it's not in the Puppet organization Puppet teams can't be
referenced in the file. This removes Puppet teams from the file, with
the option to replace individual usernames for those interested in
continuing to maintain the repo.
=> (maint) Remove puppet teams from CODEOWNERS file

lib/beaker-puppet/install_utils/foss_utils.rb, setup/git/000_EnvSetup.rb
Ruby 2.7 ships with RubyGems 3, which removed the
previously deprecated --no-ri and --no-rdoc flags
in favor of --no-document.
The --no-document flag is available since RubyGems 2.
https://github.com/rubygems/rubygems/commit/0d22d6025ce2653ec9fb20a4e0745c79bda677da
=> (maint) Remove deprecated gem install flags

lib/beaker-puppet/install_utils/foss_utils.rb, lib/beaker-puppet/install_utils/puppet_utils.rb, spec/beaker-puppet/install_utils/foss_utils_spec.rb, spec/beaker-puppet/install_utils/puppet_utils_spec.rb
Prior to this PR, if `install_puppetserver_on` was called without a version it would install the latest available nightly build.
This logic makes the use case of installing the latest *released* version unusable (i.e. from non-nightly collections), as the method
would always append `-nightly` to the collection if no version is passed.
As the `nightly` option can already be supplied to the method, change the logic to no longer assume the user wants a nightly build if they don't pass a version (or if `version: 'latest'`).
Currently, running `puppetserver_version_on` on a nightly build of puppetserver, assuming `puppetserver --version` returns something similar to:
`puppetserver version: 5.3.15.SNAPSHOT.2020.09.28T1639`
The method matches both `5.3.15` and `2020.09.28`, but returns the …
=> (maint) Make latest the latest stable instead of nightly

lib/beaker-puppet/install_utils/foss_utils.rb
Arch has a custom method to install the puppet agent. This needs to be
called, no matter if we want to install `puppet` or `puppet-agent`. Arch
Linux just has one puppet package in the repository and Puppet Inc. does
not provide custom packages/repos.
=> Fix Arch Linux support

lib/beaker-puppet/install_utils/foss_utils.rb
We recently updated packages to be signed with the new GPG key (puppet-20250406), so for the time being install both the old and the new GPG key.
=> Add both GPG keys when installing repos on SLES

lib/beaker-puppet/install_utils/foss_utils.rb
beaker has support for an `el-8-*` platform but the `install_puppet_on` function does not recognise this platform
=> Add el8 support for install_puppet_on

spec/beaker-puppet/helpers/puppet_helpers_spec.rb, spec/beaker-puppet/install_utils/windows_utils_spec.rb
Ruby 3 changed the way positional and keyword arguments work. In order
to get specs to pass when we pass in a hash we need to use braces. This PR
addresses that.
=> (maint) Update specs to fix ruby 3 spec failures

lib/beaker-puppet/install_utils/foss_utils.rb
Recent internal changes have caused http URLs to be redirected to HTTPs
for nightlies.puppet.com. This breaks the agent download from URL, but
this PR adds in some redirect logic that will fix the issue.
=> (maint) Update agent download from URL logic to handle redirects

lib/beaker-puppet/install_utils/foss_utils.rb, spec/beaker-puppet/install_utils/foss_utils_spec.rb
Add `--location` curl option, otherwise we save the redirect HTML page as the
msi, try to install that, and of course msiexec fails with 1620 since the
package is invalid.
=> (maint) Follow redirects when curling MSI

lib/beaker-puppet/install_utils/module_utils.rb
Do not igrore these files at any level in the hierarchy, only at the
root of the copied data.
=> Igrore files at the root level only

beaker-puppet.gemspec
This is also the version we use in CI. This doesn't drop support for
older rubies, it just documents what we already support.
=> Depend on Ruby 2.4 or newer in gemspec

setup/common/003_solaris_cert_fix.rb, tasks/ci.rake
A recent change to the way puppet-agent is packaged requires versions
of Solaris that are older then 11.3 to install a new cert.
The Puppet VM images for Solaris for 11, 11.2, and Solaris-Sparc need to
be updated to include the updating of the keystore. That will take some
time to accomplish, as a work around we are going to update the keystore
as part of a pre-suite.
Once we update our vmpooler images for the three versions we can remove
the pre-suite step.
Any other OS will skip the pre-suite step.
=> (PA-4331) Add a step for updating Solaris CA Keystore

lib/beaker-puppet/install_utils/foss_defaults.rb, lib/beaker-puppet/install_utils/puppet5.rb, spec/beaker-puppet/install_utils/foss_utils_spec.rb
We are encountering some firewall issues due to download links
to builds.delivery.puppetlabs.net going over HTTP instead of
HTTPS. This changes the builds links to HTTPS along with other
download URLs (e.g. nightlies, yum, etc.).
=> (PA-4332) Changes download links to HTTPS

setup/common/003_solaris_cert_fix.rb
Solaris 11 SPARC is currently missing the CA for USERTrust,
which is the root CA that Puppet's current SSL vendor, Gandi,
uses.
Missing this root CA causes an error with `curl`: "(60) SSL
certificate problem: unable to get local issuer certificate"
This adds that cert in an existing setup step.
=> (maint) Adds CA to Solaris 11 SPARC setup

setup/common/003_solaris_cert_fix.rb
I mistakenly changed the logic in the Solaris certificate setup
step to include all machines. This commit adds logic to constrain
the Solaris certificate setup step to only run for Solaris 11
machines.
=> (maint) Fixes Solaris cert setup step

lib/beaker-puppet/install_utils/windows_utils.rb, spec/beaker-puppet/install_utils/puppet_utils_spec.rb, spec/beaker-puppet/install_utils/windows_utils_spec.rb
The powershell command to test if the file exists and get its contents did not
work correctly due to spaces, resulting in errors like:
$ powershell.exe -ExecutionPolicy Bypass -InputFormat None -NoLogo -NoProfile -NonInteractive -Command Test-Path "${env:ProgramFiles}/Puppet Labs/puppet/misc/versions.txt"
Test-Path : A positional parameter cannot be found that accepts argument 'Labs/puppet/misc/versions.txt'.
Using powershell to read the file contents is slow and requires multiple levels
of escaping so that `${env:ProgramFiles}` is not interpolated and that spaces
are handled correctly. Now it prints:
$ cmd /c type '%PROGRAMFILES%\Puppet Labs\puppet\misc\versions.txt'
cleanup
facter 4.2.10-12-gb29fe9965
hiera 3.9.0-2-g84dbdb6
...
=> Actually print the versions.txt file

setup/common/005_redhat_subscription_fix.rb, tasks/ci.rake
We are consistently encountering an issue with RedHat Enterprise
Linux 8 on little-endian PowerPC where yum/dnf cannot fetch
repository metadata due to a perceived subscription issue.
This commit disables then reenables that repository, which seems
to work around the issue.
See https://access.redhat.com/discussions/4656371#comment-1769061
=> (ITSYS-2543) Adds workaround for EL8 PPCLE

tasks/ci.rake
The IP space used in the example currently is real, registered IP space. This uses RFC 5737 IP space for examples (TEST-NET-1) instead.
=> (maint) Uses RFC 5737 IP space in example

README.md, lib/beaker-puppet/helpers/puppet_helpers.rb
This makes it easy to make apply_manifest run with debug logging.
=> Introduce BEAKER_PUPPET_DEBUG env var

setup/common/003_solaris_cert_fix.rb
The DigiCert root CA G4 cert is named `DigiCert_Trusted_Root_G4.pem` on a fully patched Solaris 11.4 system. This resolves a duplicate certificate error after restarting ca-certificates.
=> Fix DigiCert root cert to match fully patched Solaris 11.4

Gemfile, Rakefile, lib/beaker-puppet/install_utils/module_utils.rb, spec/beaker-puppet/install_utils/module_utils_spec.rb, tasks/ci.rake
The `exists?` method has long been deprecated and has been officially removed as of Ruby 3.2.0.
=> (maint) Call `exist?` instead of `exists?`

lib/beaker-puppet/install_utils/foss_utils.rb
without this the data from foss_defaults is not properly loaded, leading to errors like:
Beaker::Host::CommandFailure:
Host 'freebsd12-64-1' exited with 64 running:
mkdir -p
Last 100 lines of output were:
usage: mkdir [-pv] [-m mode] directory_name ...
=> configure defaults on FreeBSD

beaker-puppet.gemspec
Beaker itself depends on this. While in the tests it is used, we can rely on Beaker to specify the dependency.
=> Drop in-parallel dependency

lib/beaker-puppet/install_utils/foss_utils.rb
In the Perforce/Puppet infrastructure, certain OS images have *puppet* in the file system that aren't modifiable. Since this is just a sort of best effort to remove puppet related files, we should loosen the expectations and notify in the log if something goes awry, but still continue execution.
=> Loosen expectations while attempting to delete puppet related files

lib/beaker-puppet/install_utils/foss_utils.rb
Added platform support for Amazon Linux 2023
This change is done as part of [PE-37297] (This is internal to Puppet Team)
=> Add Amazon linux 2023 platform support

tasks/ci.rake
When running `ci:test:aio` make sure `beaker exec post-suite` executes
When running `ci:test:aio[true]` make sure `beaker destroy` executes
Fixes #237
=> Ensure post-suite and destroy execute

README.md
Was transferred back to Puppetlabs, see #229.
=> README: remove obsolete transfer notice, update badges

setup/aio/010_Install_Puppet_Agent.rb
If the `DEV_BUILD_PATH` environment variable is set and refers to a puppet-agent package, then it will be scp'ed to the remote system and installed. This makes it possible to run beaker tests on a platform without needing to generate repos or ship artifacts.
export DEV_BUILD_PATH=/home/josh/work/puppet-agent/output/sles/12/puppet8/x86_64/puppet-agent-8.3.1.65.gc65ba7001-1.sles12.x86_64.rpm
floaty get sles-12-x86_64
bundle exec beaker-hostgenerator 'sles12-64a{hypervisor=none,vmhostname=<hostname>}' > hosts.yaml
bundle exec rake ci:test:setup SHA=8.3.1 HOSTS=hosts.yaml
bundle exec beaker exec <test>
Where `<hostname>` is the fqdn of the remote system and `<test>` is the file or directory of tests to execute against the remote system.
=> Add the ability to install puppet-agent from a local dev build

.github/workflows/auto_release_prep.yml, .github/workflows/release.yml
This commit replaces the release process implemented by Vox Pupuli with Puppet's gem release GitHub Actions.
=> Move to Puppet release GitHub Actions

release-prep.sh
This commit adds the release script prep necessary for calling the auto_release_prep workflow.
This script is taken from https://github.com/puppetlabs/release-engineering-repo-standards
=> Add release prep script

tasks/ci.rake
beaker command should be exec with bundle if the ci task was executed with bundle
=> fix beaker exec when called from bundle exec

release-prep.sh
The release-prep script was originally taken from the RE repo standards repository: https://github.com/puppetlabs/release-engineering-repo-standards
However, a more recent version of the script can be found in the Tefoji repo: https://github.com/puppetlabs/tefoji/blob/main/release-prep
The version committed here has a lower Ruby version (as beaker-puppet is not yet compatible with Ruby >= 3.2).
=> Update release-prep script

.github_changelog_generator
Previously, this project used the "skip-changelog" label on PRs to denote PRs that were trivial enough to not include in changelog generation.
However, the auto_release_prep workflow that we use to generate changelogs makes the assumption that the caller repository uses a "maintenance" label. The workflow errors if the caller repository does not use that label.
I have renamed the "skip-changelog" label to "maintenance" to account for this discrepancy between this project and the release prep workflow.
This commit updates the GitHub changelog generator configuration file to exclude the "maintenance" label instead of "skip-changelog."
=> Update excluded label to "maintenance"

.github/workflows/release.yml, .github/workflows/test.yml, lib/beaker-puppet/install_utils/foss_utils.rb
Cherry pick the change from the main/3.x version and cherry-pick necessary `.github/*` changes.
=> Add amazon linux support to the 2.x branch 

lib/beaker-puppet/install_utils/foss_utils.rb, spec/beaker-puppet/install_utils/foss_utils_spec.rb, spec/helpers.rb
This needs testing but I'd like to get this in before the next major release of beaker-puppet.
=> Remove unsupported network platforms

lib/beaker-puppet/install_utils/puppet5.rb, spec/beaker-puppet/install_utils/puppet5_spec.rb
Ubuntu 24.04 ships a puppet-agent 8 package which uses different paths than ours. To ensure we install the correct puppet-agent package, install the specific puppet-agent artifact.
=> Install puppet-agent directly on Ubuntu 24.04

CHANGELOG.md, lib/beaker-puppet/version.rb
github_changelog_generator sorts based on tag date instead of semantic version,
so the changelog has been manually updated so that 2.1.0 comes between 2.0.0 and 3.0.0
=> Release prep 4.1.0

.github/workflows/test.yml, beaker-puppet.gemspec, lib/beaker-puppet.rb, lib/beaker-puppet/helpers/puppet_helpers.rb, lib/beaker-puppet/helpers/tk_helpers.rb, lib/beaker-puppet/inifile.rb, spec/beaker-puppet/helpers/facter_helpers_spec.rb
The `inifile` gem has not been updated in 10+ years and does not run on Ruby 3.2 because it relies on String#taint. There is a o-inifile gem, but it has the same `taint` problem.
So vendor the MIT licensed `inifile` code into beaker-puppet and update it for Ruby 3.2. According to https://fossa.com/blog/open-source-licenses-101-mit-license/ in order to copy and/or modify the code we need to:
1. Provide the original copyright notice
2. A copy of the license itself
I've included both of those in `inifile.rb`
rubocop is failing because of an incompatibility with `rubocop-factory_bot` and `rubocop-rspec_rails`, see https://github.com/puppetlabs/dependency_checker/pull/72#issue-2343540667 for an example. That issue is fixed in https://github.com/puppetlabs/beaker-puppet/pull/263
=> (PA-7091) Vendor inifile in beaker-puppet

CHANGELOG.md, lib/beaker-puppet/version.rb
Add support for Ruby 3.2 and 3.3
=> Release prep 4.2.0
